version: "3"
services:
  my-app:
    image: manhtientran/url-shortener:1.2
    ports:
      - 5000:5000
    environment:
      - HOST_NAME=http://cyberapis.xyz
      - PORT=5000
  redis-app:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
