version: "3"
services:
  my-app:
    image: manhtientran/url-shortener
    ports:
      - 5000:5000
    environment:
      - HOST_NAME: https://cyberapis.xyz/
  redis-app:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
